/// Bitget trade/rest/ws error codes to short descriptions.
pub fn describe_trade_error_code(code: i32) -> Option<&'static str> {
    match code {
        0 => Some("Success"),
        25001 => Some("Operation timed out"),
        25120 => Some("Current mode does not support leverage"),
        40015 => Some("System error, retry later"),
        40715 => Some("Order size exceeds max open size"),
        40774 => Some("One-way position account requires one-way order type"),
        40798 => Some("Contract account balance insufficient"),
        40800 => Some("Insufficient margin amount"),
        40815 => Some("Order price above max buy price"),
        40816 => Some("Order price below min sell price"),
        40910 => Some("Operation timed out"),
        40911 => Some("Request timestamp expired"),
        40931 => Some("Duplicated clientOid"),
        43001 => Some("Order does not exist"),
        43002 => Some("Order placement failed"),
        43003 => Some("Order placement failed"),
        43004 => Some("No cancellable order"),
        43012 => Some("Account balance insufficient"),
        43118 => Some("Duplicated clientOrderId"),
        45001 => Some("Unknown error"),
        45002 => Some("Asset available insufficient"),
        45003 => Some("Open available insufficient"),
        45031 => Some("Order already terminal"),
        45055 => Some("Order cannot be canceled in current status"),
        45057 => Some("Order does not exist"),
        50018 => Some("Price must be greater than zero"),
        50060 => Some("Duplicated clientOid"),
        59014 => Some("Parameter precision error"),
        22001 => Some("No order to cancel"),
        22006 => Some("Order price above risk-control max buy price"),
        22007 => Some("Order price below risk-control min sell price"),
        22008 => Some("Market price above risk-control max buy price"),
        22009 => Some("Market price below risk-control min sell price"),
        22010 => Some("IP whitelist required"),
        22029 => Some("Max open size exceeded by risk control"),
        22030 => Some("Reduce-only conflict with existing orders"),
        22034 => Some("Below minimum order quantity"),
        22038 => Some("Quantity step mismatch"),
        22045 => Some("Orderbook liquidity insufficient"),
        22046 => Some("Price below minimum price limit"),
        22047 => Some("Price above maximum price limit"),
        45110 => Some("Triggered minimum order value limit"),
        45111 => Some("Triggered minimum order quantity"),
        45112 => Some("Triggered maximum order quantity"),
        45113 => Some("Triggered maximum order value limit"),
        45115 => Some("Price tick mismatch"),
        70228 => Some("Too many requests"),
        70229 => Some("Order placement failed"),
        _ => None,
    }
}
