[package]
name = "trade_signal"
version.workspace = true
edition.workspace = true

[dependencies]
account_common = { path = "../account_common" }
anyhow.workspace = true
bytes = { version = "1.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
depth_pub_common = { package = "depth_pub", path = "../depth_pub" }
env_logger = "0.10"
factor_engine = { path = "../factor_engine" }
hex = "0.4"
hmac = "0.12"
iceoryx2 = "0.8.1"
ipc_common = { path = "../ipc_common" }
log = "0.4"
mkt_parsers = { path = "../mkt_parsers" }
order_common = { path = "../order_common" }
quote_plan = { path = "../quote_plan" }
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
reqwest = { version = "0.12.19", features = ["json", "blocking"] }
rolling_common = { path = "../rolling_common" }
runtime_common = { path = "../runtime_common" }
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
sha2 = "0.10"
signal_common = { path = "../signal_common" }
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7.15"
urlencoding = "2.1"

[dev-dependencies]
signal_common = { path = "../signal_common", features = ["test-utils"] }
