[[binance]]
BINANCE_API_KEYc = 'z9rb55Ix9vyBvzHjYVxZT0mRshd9Qyvvs40vKoCZPhb7FWwAbiUVVsdfQXv5AHHZ'
BINANCE_API_SECRET = 'yVYqipzjCe7S7Eydc4kAEMbEvi68Qmo2un91CAm0lOIXaY5vdoXf4W3YW5dNYkYw'

[[okex]]

[[bybit]]