[[binance]]
BINANCE_API_KEY='JepyQ7PWJ4BsnGRJ6VxFCyKlrzB27o7T6sBr5pn4lGY83lC3y3q6iw5nkQRF2bOv'
BINANCE_API_SECRET='eqcMOXuhDhSgyzRBXtamoN7qBA2pBtpGsKoEIHoqynvtDdBxJdrhylJvjVraND85'

[[okex]]

[[bybit]]