# 内部会创建两个连接，自动以奇偶间隔错开重启
restart_duration_secs: 1800

# 主备连接使用的本地IP地址
primary_local_ip: "172.31.33.133"     # 主连接绑定的本地IP，0.0.0.0表示默认
secondary_local_ip: "172.31.46.90"   # 备连接绑定的本地IP，0.0.0.0表示默认
snapshot_requery_time: ""  # "--:--:--" 表示立即查询(30秒后)，空字符串禁用快照，可设置如 "02:00:00" 定时查询
symbol_socket: "/home/ubuntu/crypto_mkt/symbol_server/exchange"

# 数据类型开关配置
data_types:
  enable_incremental: true    # 增量orderbook数据
  enable_trade: true          # 逐笔成交数据
  enable_kline: true          # K线数据
  enable_derivatives: true    # 衍生品指标数据（仅期货交易所）
  enable_ask_bid_spread: true # 买卖价差（最优买卖价）数据

# IceOryx配置
iceoryx:
  # IceOryx会自动根据交易所名称创建频道
  # 频道格式: data_pubs/{exchange}/{data_type}
  # 例如: data_pubs/binance/incremental, data_pubs/binance-futures/derivatives
  
  # 历史记录和订阅者配置
  incremental:
    history_size: 100
    max_subscribers: 10
  
  trade:
    history_size: 100
    max_subscribers: 10
  
  kline:
    history_size: 50
    max_subscribers: 10
  
  derivatives:
    history_size: 50
    max_subscribers: 10
  
  ask_bid_spread:
    history_size: 100
    max_subscribers: 10
  
  signal:
    history_size: 50
    max_subscribers: 10