[[binance]]
BINANCE_API_KEY='6JxKPXSFYKe0yJnX3QAWma3dcTyq9mkUgVrFzV1eJnxm0JIB0pbJKzJpVYaNQ1cN'
BINANCE_API_SECRET='KiTvZkaHlPhoH6Mi7csFwOIJ6qdqVjNmOTkmwdNsx5Rg3M2VVjlX7KrPz3Wofqlj'

[[okex]]

[[bybit]]