[[binance]]
BINANCE_API_KEY='IUnLwpUM6eg8EB7ADo3iR6nv6IZLJhG2DqlIqnx74XrZa9yTrAnHqf0DXXjtlyXu'
BINANCE_API_SECRET='YBbyYGqGHHYua4Uc00569wvKW6g4O7iGXNeeFdJqBtQ3TtuQZ3QrLpDnRhqoK9B0'

[[okex]]

[[bybit]]