model_manager_base_url = "http://127.0.0.1:6300"
model_manager_request_timeout_ms = 120000
tlen_server_base_url = "http://127.0.0.1:6322"
tlen_server_request_timeout_ms = 5000

# 直接填写完整 service 名称，不做 {model_name} 替换。
input_service = "fusion_factor/binance-futures"
output_service = "model_output/binance_futures_direction_model"

[score_rolling]
params_hash_key_template = "model_score_rolling_params_{model_name}"
output_hash_key_template = "model_score_rolling_thresholds_{model_name}"
reload_param_sec = 60
max_length = 150000
rolling_window = 17800
min_periods = 100
quantiles = [0.9, 0.8, 0.2, 0.1]
