# PairMM Resample 配置

pairmm_resample:
  resample_interval_ms: 1000
  online_symbols:
    - "BTCUSDT"
  factor_names:
    - "history_threshold"
    - "model_threshold"
    - "cancel_threshold"
    - "factor1"
    - "factor2"
