[http]
bind = "0.0.0.0"
port = 4190 
ws_path = "/ws" 
# cors_origins = ["https://your-frontend.example.com"] 
# auth_token = "optional-token" 

[sampling] 
interval_ms = 200 
send_if_changed = false 
# symbols = ["BTCUSDT","ETHUSDT"] # 可选，输出过滤 

[thresholds] 
open = 0.002 
close = 0.0005 
