[[servers]]
namespaces = ["okex_fr_trade"]
[servers.http]
bind = "0.0.0.0"
port = 10011
ws_path = "/ws"
[servers.pre_trade]
enabled = true

[[servers]]
namespaces = ["gate_fr_trade"]
[servers.http]
bind = "0.0.0.0"
port = 10021
ws_path = "/ws"
[servers.pre_trade]
enabled = true

[[servers]]
namespaces = ["binance_fr_trade"]
[servers.http]
bind = "0.0.0.0"
port = 10031
ws_path = "/ws"
[servers.pre_trade]
enabled = true
