period = "2021-07-01_2022-07-01"
parsed_staging_dir = "/mnt/nvme-raid0-28t/fanghaizhou/lseg_data/usstock_raw_parsed_by_ric/2021-07-01_2022-07-01"
rocksdb_dir = "/mnt/nvme-raid0-28t/fanghaizhou/lseg_data/usstock_raw_rocksdb/2021-07-01_2022-07-01"
progress_every = 1000000
keep_temporary_column_families = false
workers = 32
direction_calendar = "/mnt/nvme-raid0-28t/liang_torch/usstock_data/work/nyse_rth_20210628_20260705.csv"
