use crate::common::{bytes_helper, SignalBytes, SignalSliceReader, TradingLeg};
use crate::tick_math::QuantizedValue;
use bytes::{Buf, BufMut, Bytes, BytesMut};
use order_common::Side;

fn fixed_symbol_to_string(symbol: &[u8; 32]) -> String {
    let end = symbol.iter().position(|&b| b == 0).unwrap_or(32);
    String::from_utf8_lossy(&symbol[..end]).to_string()
}

fn set_fixed_symbol(dst: &mut [u8; 32], symbol: &str) {
    *dst = [0u8; 32];
    let bytes = symbol.as_bytes();
    let len = bytes.len().min(32);
    dst[..len].copy_from_slice(&bytes[..len]);
}

fn write_i32_to_slice(out: &mut [u8], offset: usize, value: i32) -> Option<()> {
    let end = offset.checked_add(4)?;
    out.get_mut(offset..end)?
        .copy_from_slice(&value.to_le_bytes());
    Some(())
}

fn write_u64_to_slice(out: &mut [u8], offset: usize, value: u64) -> Option<()> {
    let end = offset.checked_add(8)?;
    out.get_mut(offset..end)?
        .copy_from_slice(&value.to_le_bytes());
    Some(())
}

fn write_f64_to_slice(out: &mut [u8], offset: usize, value: f64) -> Option<()> {
    let end = offset.checked_add(8)?;
    out.get_mut(offset..end)?
        .copy_from_slice(&value.to_le_bytes());
    Some(())
}

fn write_fixed_symbol_to_slice(out: &mut [u8], offset: usize, symbol: &[u8; 32]) -> Option<usize> {
    let end = symbol.iter().position(|&b| b == 0).unwrap_or(32);
    let len_slot = out.get_mut(offset)?;
    *len_slot = end as u8;
    let start = offset.checked_add(1)?;
    let stop = start.checked_add(end)?;
    out.get_mut(start..stop)?.copy_from_slice(&symbol[..end]);
    Some(stop)
}

fn write_qv(buf: &mut BytesMut, qv: &QuantizedValue) {
    let (tick_i64, tick_exp) = qv.get_tick_parts();
    buf.put_i64_le(tick_i64);
    buf.put_i32_le(tick_exp);
    buf.put_i64_le(qv.get_count());
}

/// Market maker hedge signal context (query response)
#[derive(Debug, Clone)]
pub struct MmHedgeCtx {
    /// Market leg snapshot
    pub opening_leg: TradingLeg,

    /// Leg symbol
    pub opening_symbol: [u8; 32],

    /// Price levels encoded by QuantizedValue (same encoding style as MmOpenCtx::price_qv)
    pub price_qv_list: Vec<QuantizedValue>,

    /// Amount levels encoded by QuantizedValue (same encoding style as MmOpenCtx::amount_qv)
    pub amount_qv_list: Vec<QuantizedValue>,

    /// Explicit price offsets aligned with `price_qv_list`
    pub price_offsets: Vec<f64>,

    /// Queried tlen values aligned with `price_qv_list`
    pub tlen_values: Vec<f64>,

    /// Signal timestamp (microseconds)
    pub signal_ts: i64,

    /// Next query timestamp (microseconds)
    pub next_query_ts: i64,

    /// Hedge query request sequence generated by pre-trade.
    /// Re-sent watchdog queries must reuse the same sequence so pre-trade
    /// can accept the first valid reply and drop later duplicates.
    pub request_seq: u64,

    /// Whether downstream should place a taker/market hedge order.
    pub use_taker: bool,

    /// From key length
    pub from_key_len: u32,

    /// From key bytes
    pub from_key: Vec<u8>,
}

/// Arb hedge state query response context.
///
/// 和 MM hedge query response 的语义接近，但这里只保留一个 hedge 单和一个 offset。
/// ArbHedgeStrategy 拿到 price/amount 的 QV 后生成订单并维护 pending borrow/release。
#[derive(Debug, Clone)]
pub struct ArbHedgeCtx {
    /// Arb hedge strategy id.
    pub strategy_id: i32,

    /// Hedge side (Buy/Sell), stored as u8.
    pub hedge_side: u8,

    /// Hedge market snapshot.
    pub hedging_leg: TradingLeg,

    /// Hedge symbol.
    pub hedging_symbol: [u8; 32],

    /// One hedge price encoded by QuantizedValue.
    pub price_qv: QuantizedValue,

    /// One hedge amount encoded by QuantizedValue.
    pub amount_qv: QuantizedValue,

    /// The queried offset used to produce `price_qv`.
    pub price_offset: f64,

    /// Signal timestamp (microseconds).
    pub signal_ts: i64,

    /// Hedge order expiration time (microseconds). 0 means taker/market order.
    pub exp_time: i64,

    /// Pre-trade owned request sequence.
    pub request_seq: u64,

    /// From key length.
    pub from_key_len: u32,

    /// From key bytes.
    pub from_key: Vec<u8>,
}

impl Default for MmHedgeCtx {
    fn default() -> Self {
        Self::new()
    }
}

impl MmHedgeCtx {
    /// Create new market maker hedge context
    pub fn new() -> Self {
        Self {
            opening_leg: TradingLeg {
                venue: 0,
                bid0: 0.0,
                ask0: 0.0,
                ts: 0,
            },
            opening_symbol: [0u8; 32],
            price_qv_list: Vec::new(),
            amount_qv_list: Vec::new(),
            price_offsets: Vec::new(),
            tlen_values: Vec::new(),
            signal_ts: 0,
            next_query_ts: 0,
            request_seq: 0,
            use_taker: false,
            from_key_len: 0,
            from_key: Vec::new(),
        }
    }

    /// Set opening leg symbol
    pub fn set_opening_symbol(&mut self, symbol: &str) {
        let bytes = symbol.as_bytes();
        let len = bytes.len().min(32);
        self.opening_symbol[..len].copy_from_slice(&bytes[..len]);
    }

    /// Get opening leg symbol
    pub fn get_opening_symbol(&self) -> String {
        let end = self
            .opening_symbol
            .iter()
            .position(|&b| b == 0)
            .unwrap_or(32);
        String::from_utf8_lossy(&self.opening_symbol[..end]).to_string()
    }

    /// Set from key bytes (updates length)
    pub fn set_from_key(&mut self, from_key: Vec<u8>) {
        self.from_key_len = from_key.len() as u32;
        self.from_key = from_key;
    }

    pub fn is_taker(&self) -> bool {
        self.use_taker
    }
}

impl Default for ArbHedgeCtx {
    fn default() -> Self {
        Self::new()
    }
}

impl ArbHedgeCtx {
    pub fn new() -> Self {
        Self {
            strategy_id: 0,
            hedge_side: 0,
            hedging_leg: TradingLeg {
                venue: 0,
                bid0: 0.0,
                ask0: 0.0,
                ts: 0,
            },
            hedging_symbol: [0u8; 32],
            price_qv: QuantizedValue::zero(),
            amount_qv: QuantizedValue::zero(),
            price_offset: 0.0,
            signal_ts: 0,
            exp_time: 0,
            request_seq: 0,
            from_key_len: 0,
            from_key: Vec::new(),
        }
    }

    pub fn set_hedging_symbol(&mut self, symbol: &str) {
        set_fixed_symbol(&mut self.hedging_symbol, symbol);
    }

    pub fn get_hedging_symbol(&self) -> String {
        fixed_symbol_to_string(&self.hedging_symbol)
    }

    pub fn get_side(&self) -> Option<Side> {
        Side::from_u8(self.hedge_side)
    }

    pub fn set_side(&mut self, side: Side) {
        self.hedge_side = side.to_u8();
    }

    pub fn set_from_key(&mut self, from_key: Vec<u8>) {
        self.from_key_len = from_key.len() as u32;
        self.from_key = from_key;
    }

    pub fn set_price_with_tick_floor(&mut self, price: f64, preferred_tick: f64) -> bool {
        let fallback = !(preferred_tick.is_finite() && preferred_tick > 0.0);
        self.price_qv = QuantizedValue::encode_floor(price, preferred_tick)
            .unwrap_or_else(QuantizedValue::zero);
        fallback
    }

    pub fn set_amount_with_tick_floor(&mut self, amount: f64, preferred_tick: f64) -> bool {
        let fallback = !(preferred_tick.is_finite() && preferred_tick > 0.0);
        self.amount_qv = QuantizedValue::encode_floor(amount, preferred_tick)
            .unwrap_or_else(QuantizedValue::zero);
        fallback
    }

    pub fn price_value(&self) -> f64 {
        self.price_qv.get_val()
    }

    pub fn amount_value(&self) -> f64 {
        self.amount_qv.get_val()
    }

    pub fn price_count(&self) -> i64 {
        self.price_qv.get_count()
    }

    pub fn amount_count(&self) -> i64 {
        self.amount_qv.get_count()
    }

    pub fn is_maker(&self) -> bool {
        self.exp_time > 0
    }

    pub fn is_taker(&self) -> bool {
        self.exp_time == 0
    }
}

impl SignalBytes for ArbHedgeCtx {
    fn to_bytes(&self) -> Bytes {
        let mut buf = BytesMut::new();

        buf.put_i32_le(self.strategy_id);
        buf.put_u8(self.hedge_side);

        buf.put_u8(self.hedging_leg.venue);
        buf.put_f64_le(self.hedging_leg.bid0);
        buf.put_f64_le(self.hedging_leg.ask0);
        buf.put_i64_le(self.hedging_leg.ts);
        bytes_helper::write_fixed_bytes(&mut buf, &self.hedging_symbol);

        write_qv(&mut buf, &self.price_qv);
        write_qv(&mut buf, &self.amount_qv);
        buf.put_f64_le(self.price_offset);
        buf.put_i64_le(self.signal_ts);
        buf.put_i64_le(self.exp_time);
        buf.put_u64_le(self.request_seq);

        let from_key_len = self.from_key.len() as u32;
        buf.put_u32_le(from_key_len);
        buf.put_slice(&self.from_key);

        buf.freeze()
    }

    fn from_bytes(bytes: Bytes) -> Result<Self, String> {
        Self::from_slice(bytes.as_ref())
    }
}

impl SignalBytes for MmHedgeCtx {
    fn to_bytes(&self) -> Bytes {
        let mut buf = BytesMut::new();

        // Opening leg
        buf.put_u8(self.opening_leg.venue);
        buf.put_f64_le(self.opening_leg.bid0);
        buf.put_f64_le(self.opening_leg.ask0);
        buf.put_i64_le(self.opening_leg.ts);
        bytes_helper::write_fixed_bytes(&mut buf, &self.opening_symbol);

        // Price qv list
        buf.put_u32_le(self.price_qv_list.len() as u32);
        for price_qv in &self.price_qv_list {
            let (tick_i64, tick_exp) = price_qv.get_tick_parts();
            buf.put_i64_le(tick_i64);
            buf.put_i32_le(tick_exp);
            buf.put_i64_le(price_qv.get_count());
        }

        // Amount qv list
        buf.put_u32_le(self.amount_qv_list.len() as u32);
        for amount_qv in &self.amount_qv_list {
            let (tick_i64, tick_exp) = amount_qv.get_tick_parts();
            buf.put_i64_le(tick_i64);
            buf.put_i32_le(tick_exp);
            buf.put_i64_le(amount_qv.get_count());
        }

        // offset list
        buf.put_u32_le(self.price_offsets.len() as u32);
        for offset in &self.price_offsets {
            buf.put_f64_le(*offset);
        }

        // tlen list
        buf.put_u32_le(self.tlen_values.len() as u32);
        for tlen in &self.tlen_values {
            buf.put_f64_le(*tlen);
        }

        // Signal timestamp
        buf.put_i64_le(self.signal_ts);

        // Next query timestamp
        buf.put_i64_le(self.next_query_ts);

        // from_key
        let from_key_len = self.from_key.len() as u32;
        buf.put_u32_le(from_key_len);
        buf.put_slice(&self.from_key);

        buf.put_u64_le(self.request_seq);
        buf.put_u8(if self.use_taker { 1 } else { 0 });

        buf.freeze()
    }

    fn from_bytes(bytes: Bytes) -> Result<Self, String> {
        Self::from_slice(bytes.as_ref())
    }
}

impl ArbHedgeCtx {
    pub fn from_slice(raw: &[u8]) -> Result<Self, String> {
        let mut reader = SignalSliceReader::new(raw);
        let strategy_id = reader.read_i32_le("ArbHedgeCtx strategy_id")?;
        let hedge_side = reader.read_u8("ArbHedgeCtx side")?;
        let (hedging_leg, hedging_symbol) = reader.read_trading_leg(true, "ArbHedgeCtx leg")?;
        let price_qv = read_qv_slice(&mut reader, "ArbHedgeCtx price_qv")?;
        let amount_qv = read_qv_slice(&mut reader, "ArbHedgeCtx amount_qv")?;
        let price_offset = reader.read_f64_le("ArbHedgeCtx price_offset")?;
        let signal_ts = reader.read_i64_le("ArbHedgeCtx signal_ts")?;
        let exp_time = reader.read_i64_le("ArbHedgeCtx exp_time")?;
        let request_seq = reader.read_u64_le("ArbHedgeCtx request_seq")?;
        let from_key_len = reader.read_u32_le("ArbHedgeCtx from_key_len")? as usize;
        let from_key = reader
            .read_bytes(from_key_len, "ArbHedgeCtx from_key")?
            .to_vec();
        reader.finish_exact("ArbHedgeCtx")?;
        Ok(Self {
            strategy_id,
            hedge_side,
            hedging_leg,
            hedging_symbol,
            price_qv,
            amount_qv,
            price_offset,
            signal_ts,
            exp_time,
            request_seq,
            from_key_len: from_key.len() as u32,
            from_key,
        })
    }
}

impl MmHedgeCtx {
    pub fn from_slice(raw: &[u8]) -> Result<Self, String> {
        const QV_BYTES_LEN: usize = 8 + 4 + 8;
        let mut reader = SignalSliceReader::new(raw);
        let (opening_leg, opening_symbol) = reader.read_trading_leg(true, "opening leg")?;

        let price_len = reader.read_u32_le("price_qv_list length")? as usize;
        let price_bytes = price_len
            .checked_mul(QV_BYTES_LEN)
            .ok_or_else(|| "price_qv_list byte length overflow".to_string())?;
        if reader.remaining() < price_bytes {
            return Err(format!(
                "Not enough bytes for price_qv_list: need {}, have {}",
                price_bytes,
                reader.remaining()
            ));
        }
        let mut price_qv_list = Vec::with_capacity(price_len);
        for _ in 0..price_len {
            price_qv_list.push(read_qv_slice(&mut reader, "MmHedgeCtx price_qv")?);
        }

        let amount_len = reader.read_u32_le("amount_qv_list length")? as usize;
        let amount_bytes = amount_len
            .checked_mul(QV_BYTES_LEN)
            .ok_or_else(|| "amount_qv_list byte length overflow".to_string())?;
        if reader.remaining() < amount_bytes {
            return Err(format!(
                "Not enough bytes for amount_qv_list: need {}, have {}",
                amount_bytes,
                reader.remaining()
            ));
        }
        let mut amount_qv_list = Vec::with_capacity(amount_len);
        for _ in 0..amount_len {
            amount_qv_list.push(read_qv_slice(&mut reader, "MmHedgeCtx amount_qv")?);
        }
        if price_qv_list.len() != amount_qv_list.len() {
            return Err(format!(
                "price_qv_list/amount_qv_list length mismatch: price_len={} amount_len={}",
                price_qv_list.len(),
                amount_qv_list.len()
            ));
        }

        let price_offset_len = reader.read_u32_le("price_offsets length")? as usize;
        let price_offset_bytes = price_offset_len
            .checked_mul(8)
            .ok_or_else(|| "price_offsets byte length overflow".to_string())?;
        if reader.remaining() < price_offset_bytes {
            return Err(format!(
                "Not enough bytes for price_offsets: need {}, have {}",
                price_offset_bytes,
                reader.remaining()
            ));
        }
        let mut price_offsets = Vec::with_capacity(price_offset_len);
        for _ in 0..price_offset_len {
            price_offsets.push(reader.read_f64_le("MmHedgeCtx price_offset")?);
        }
        if price_qv_list.len() != price_offsets.len() {
            return Err(format!(
                "price_qv_list/price_offsets length mismatch: price_len={} offset_len={}",
                price_qv_list.len(),
                price_offsets.len()
            ));
        }

        let tlen_len = reader.read_u32_le("tlen_values length")? as usize;
        let tlen_bytes = tlen_len
            .checked_mul(8)
            .ok_or_else(|| "tlen_values byte length overflow".to_string())?;
        if reader.remaining() < tlen_bytes {
            return Err(format!(
                "Not enough bytes for tlen_values: need {}, have {}",
                tlen_bytes,
                reader.remaining()
            ));
        }
        let mut tlen_values = Vec::with_capacity(tlen_len);
        for _ in 0..tlen_len {
            tlen_values.push(reader.read_f64_le("MmHedgeCtx tlen")?);
        }
        if !tlen_values.is_empty() && tlen_values.len() != price_qv_list.len() {
            return Err(format!(
                "price_qv_list/tlen_values length mismatch: price_len={} tlen_len={}",
                price_qv_list.len(),
                tlen_values.len()
            ));
        }

        let signal_ts = reader.read_i64_le("MmHedgeCtx signal_ts")?;
        let next_query_ts = reader.read_i64_le("MmHedgeCtx next_query_ts")?;
        let from_key_len = reader.read_u32_le("MmHedgeCtx from_key_len")? as usize;
        let from_key = reader
            .read_bytes(from_key_len, "MmHedgeCtx from_key")?
            .to_vec();
        let request_seq = reader.read_u64_le("MmHedgeCtx request_seq")?;
        let use_taker = reader.read_u8("MmHedgeCtx use_taker")? != 0;
        reader.finish_exact("MmHedgeCtx")?;

        Ok(Self {
            opening_leg,
            opening_symbol,
            price_qv_list,
            amount_qv_list,
            price_offsets,
            tlen_values,
            signal_ts,
            next_query_ts,
            request_seq,
            use_taker,
            from_key_len: from_key.len() as u32,
            from_key,
        })
    }
}

fn read_qv_slice(
    reader: &mut SignalSliceReader<'_>,
    field: &str,
) -> Result<QuantizedValue, String> {
    let tick_i64 = reader.read_i64_le(field)?;
    let tick_exp = reader.read_i32_le(field)?;
    let count = reader.read_i64_le(field)?;
    Ok(QuantizedValue::from_parts(tick_i64, tick_exp, count))
}

/// MM 对冲查询消息（携带 symbol + 当期买/卖成交 + 累计净头寸）
#[derive(Debug, Clone)]
pub struct MmHedgeSignalQueryMsg {
    /// 交易对
    pub symbol: [u8; 32],
    /// 当期买成交量（base qty）
    pub period_buy_qty: f64,
    /// 当期卖成交量（base qty）
    pub period_sell_qty: f64,
    /// 累计净头寸（base qty，正=多，负=空）
    pub net_qty: f64,
    /// 单币敞口预算（USDT），来源 pre_trade_risk_params: max_pos_u * max_symbol_exposure_ratio
    pub symbol_exposure_u: f64,

    /// Remaining inventory weighted average price recorded by pre-trade.
    pub weighted_inventory_price: f64,

    /// Pre-trade owned hedge request sequence. A watchdog resend must keep
    /// the same sequence so the first valid reply can be accepted exactly once.
    pub request_seq: u64,
}

impl MmHedgeSignalQueryMsg {
    pub fn new(
        symbol: &str,
        period_buy_qty: f64,
        period_sell_qty: f64,
        net_qty: f64,
        symbol_exposure_u: f64,
        weighted_inventory_price: f64,
        request_seq: u64,
    ) -> Self {
        let mut symbol_bytes = [0u8; 32];
        let bytes = symbol.as_bytes();
        let len = bytes.len().min(32);
        symbol_bytes[..len].copy_from_slice(&bytes[..len]);
        Self {
            symbol: symbol_bytes,
            period_buy_qty,
            period_sell_qty,
            net_qty,
            symbol_exposure_u,
            weighted_inventory_price,
            request_seq,
        }
    }

    pub fn get_symbol(&self) -> String {
        let end = self.symbol.iter().position(|&b| b == 0).unwrap_or(32);
        String::from_utf8_lossy(&self.symbol[..end]).to_string()
    }

    pub fn to_bytes(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(self.encoded_len());
        self.write_to(&mut buf);
        buf.freeze()
    }

    pub fn encoded_len(&self) -> usize {
        1 + bytes_helper::fixed_bytes_len(&self.symbol) + 8 * 6
    }

    pub fn write_to(&self, buf: &mut BytesMut) {
        bytes_helper::write_fixed_bytes(buf, &self.symbol);
        buf.put_f64_le(self.period_buy_qty);
        buf.put_f64_le(self.period_sell_qty);
        buf.put_f64_le(self.net_qty);
        buf.put_f64_le(self.symbol_exposure_u);
        buf.put_f64_le(self.weighted_inventory_price);
        buf.put_u64_le(self.request_seq);
    }

    pub fn write_to_slice(&self, out: &mut [u8]) -> Option<()> {
        if out.len() < self.encoded_len() {
            return None;
        }
        let mut offset = write_fixed_symbol_to_slice(out, 0, &self.symbol)?;
        write_f64_to_slice(out, offset, self.period_buy_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.period_sell_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.net_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.symbol_exposure_u)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.weighted_inventory_price)?;
        offset += 8;
        write_u64_to_slice(out, offset, self.request_seq)?;
        Some(())
    }

    pub fn from_bytes(mut bytes: Bytes) -> Result<Self, String> {
        let symbol = bytes_helper::read_fixed_bytes(&mut bytes)?;
        if bytes.remaining() < 8 * 5 {
            return Err(
                "insufficient bytes for buy/sell/net qty/symbol_exposure_u/weighted_inventory_price/request_seq"
                    .to_string(),
            );
        }
        let period_buy_qty = bytes.get_f64_le();
        let period_sell_qty = bytes.get_f64_le();
        let net_qty = bytes.get_f64_le();
        let symbol_exposure_u = bytes.get_f64_le();
        let weighted_inventory_price = bytes.get_f64_le();
        let request_seq = bytes.get_u64_le();
        Ok(Self {
            symbol,
            period_buy_qty,
            period_sell_qty,
            net_qty,
            symbol_exposure_u,
            weighted_inventory_price,
            request_seq,
        })
    }
}

/// Arb hedge 状态查询消息。
///
/// 新 ArbHedgeStrategy 发出该查询，请求上游根据当前真实净头寸和已到期待对冲量生成 hedge 回包。
#[derive(Debug, Clone)]
pub struct ArbHedgeSignalQueryMsg {
    /// Arb hedge strategy id that owns this symbol-level inventory.
    pub strategy_id: i32,

    /// Internal normalized symbol.
    pub symbol: [u8; 32],

    /// open/hedge 合并后的真实净头寸，base qty 口径。
    pub net_qty: f64,

    /// 已到 close_ts、当前可尝试 hedge 的 pending qty，base qty 口径。
    pub due_hedge_qty: f64,

    /// 全部 pending qty，包含未到 close_ts 的部分。
    pub pending_hedge_qty: f64,

    /// 单币敞口预算（USDT），来源 pre_trade_risk_params: max_pos_u * max_symbol_exposure_ratio.
    pub symbol_exposure_u: f64,

    /// Remaining inventory weighted average price recorded by pre-trade.
    pub weighted_inventory_price: f64,

    /// Pre-trade owned hedge request sequence.
    pub request_seq: u64,
}

impl ArbHedgeSignalQueryMsg {
    pub fn new(
        strategy_id: i32,
        symbol: &str,
        net_qty: f64,
        due_hedge_qty: f64,
        pending_hedge_qty: f64,
        symbol_exposure_u: f64,
        weighted_inventory_price: f64,
        request_seq: u64,
    ) -> Self {
        let mut symbol_bytes = [0u8; 32];
        let bytes = symbol.as_bytes();
        let len = bytes.len().min(32);
        symbol_bytes[..len].copy_from_slice(&bytes[..len]);
        Self {
            strategy_id,
            symbol: symbol_bytes,
            net_qty,
            due_hedge_qty,
            pending_hedge_qty,
            symbol_exposure_u,
            weighted_inventory_price,
            request_seq,
        }
    }

    pub fn get_symbol(&self) -> String {
        let end = self.symbol.iter().position(|&b| b == 0).unwrap_or(32);
        String::from_utf8_lossy(&self.symbol[..end]).to_string()
    }

    pub fn to_bytes(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(self.encoded_len());
        self.write_to(&mut buf);
        buf.freeze()
    }

    pub fn encoded_len(&self) -> usize {
        4 + 1 + bytes_helper::fixed_bytes_len(&self.symbol) + 8 * 6
    }

    pub fn write_to(&self, buf: &mut BytesMut) {
        buf.put_i32_le(self.strategy_id);
        bytes_helper::write_fixed_bytes(buf, &self.symbol);
        buf.put_f64_le(self.net_qty);
        buf.put_f64_le(self.due_hedge_qty);
        buf.put_f64_le(self.pending_hedge_qty);
        buf.put_f64_le(self.symbol_exposure_u);
        buf.put_f64_le(self.weighted_inventory_price);
        buf.put_u64_le(self.request_seq);
    }

    pub fn write_to_slice(&self, out: &mut [u8]) -> Option<()> {
        if out.len() < self.encoded_len() {
            return None;
        }
        write_i32_to_slice(out, 0, self.strategy_id)?;
        let mut offset = write_fixed_symbol_to_slice(out, 4, &self.symbol)?;
        write_f64_to_slice(out, offset, self.net_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.due_hedge_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.pending_hedge_qty)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.symbol_exposure_u)?;
        offset += 8;
        write_f64_to_slice(out, offset, self.weighted_inventory_price)?;
        offset += 8;
        write_u64_to_slice(out, offset, self.request_seq)?;
        Some(())
    }

    pub fn from_bytes(mut bytes: Bytes) -> Result<Self, String> {
        if bytes.remaining() < 4 {
            return Err("insufficient bytes for strategy_id".to_string());
        }
        let strategy_id = bytes.get_i32_le();
        let symbol = bytes_helper::read_fixed_bytes(&mut bytes)?;
        if bytes.remaining() < 8 * 6 {
            return Err(
                "insufficient bytes for net/due/pending/symbol_exposure_u/weighted_inventory_price/request_seq"
                    .to_string(),
            );
        }
        let net_qty = bytes.get_f64_le();
        let due_hedge_qty = bytes.get_f64_le();
        let pending_hedge_qty = bytes.get_f64_le();
        let symbol_exposure_u = bytes.get_f64_le();
        let weighted_inventory_price = bytes.get_f64_le();
        let request_seq = bytes.get_u64_le();
        Ok(Self {
            strategy_id,
            symbol,
            net_qty,
            due_hedge_qty,
            pending_hedge_qty,
            symbol_exposure_u,
            weighted_inventory_price,
            request_seq,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{ArbHedgeCtx, MmHedgeCtx, MmHedgeSignalQueryMsg};
    use crate::common::{SignalBytes, TradingLeg};
    use crate::tick_math::QuantizedValue;
    use order_common::Side;
    use order_common::TradingVenue;

    #[test]
    fn mm_hedge_query_roundtrip() {
        let msg = MmHedgeSignalQueryMsg::new("SOLUSDT", 1.0, 0.5, 0.5, 1000.0, 101.5, 7);
        let parsed = MmHedgeSignalQueryMsg::from_bytes(msg.to_bytes()).unwrap();
        assert_eq!(parsed.get_symbol(), "SOLUSDT");
        assert!((parsed.period_buy_qty - 1.0).abs() < 1e-12);
        assert!((parsed.weighted_inventory_price - 101.5).abs() < 1e-12);
        assert_eq!(parsed.request_seq, 7);
    }

    #[test]
    fn mm_hedge_query_from_bytes_ignores_trailing_bytes() {
        let msg = MmHedgeSignalQueryMsg::new("SOLUSDT", 1.0, 0.5, 0.5, 1000.0, 101.5, 7);
        let mut raw = msg.to_bytes().to_vec();
        raw.extend_from_slice(&[1u8, 2u8, 3u8]);

        let parsed = MmHedgeSignalQueryMsg::from_bytes(bytes::Bytes::from(raw)).unwrap();
        assert_eq!(parsed.get_symbol(), "SOLUSDT");
        assert!((parsed.period_buy_qty - 1.0).abs() < 1e-12);
        assert!((parsed.weighted_inventory_price - 101.5).abs() < 1e-12);
        assert_eq!(parsed.request_seq, 7);
    }

    #[test]
    fn mm_hedge_ctx_roundtrip_with_tlen_values() {
        let mut ctx = MmHedgeCtx::new();
        ctx.opening_leg = TradingLeg::new(TradingVenue::BinanceFutures, 100.0, 100.1, 123456);
        ctx.set_opening_symbol("BTCUSDT");
        ctx.price_qv_list
            .push(QuantizedValue::from_parts(1, -1, 724310));
        ctx.amount_qv_list
            .push(QuantizedValue::from_parts(1, -3, 5000));
        ctx.price_offsets.push(0.0015);
        ctx.tlen_values.push(0.1234);
        ctx.signal_ts = 111;
        ctx.next_query_ts = 222;
        ctx.request_seq = 9;
        ctx.use_taker = true;
        ctx.set_from_key(b"fk".to_vec());

        let parsed = MmHedgeCtx::from_bytes(ctx.to_bytes()).unwrap();
        assert_eq!(parsed.get_opening_symbol(), "BTCUSDT");
        assert_eq!(parsed.price_qv_list.len(), 1);
        assert_eq!(parsed.amount_qv_list.len(), 1);
        assert_eq!(parsed.price_offsets, vec![0.0015]);
        assert_eq!(parsed.tlen_values, vec![0.1234]);
        assert_eq!(parsed.signal_ts, 111);
        assert_eq!(parsed.next_query_ts, 222);
        assert_eq!(parsed.request_seq, 9);
        assert!(parsed.use_taker);
        assert_eq!(parsed.from_key, b"fk");
    }

    #[test]
    fn arb_hedge_ctx_roundtrip_single_order_single_offset() {
        let mut ctx = ArbHedgeCtx::new();
        ctx.strategy_id = 11;
        ctx.set_side(Side::Sell);
        ctx.hedging_leg = TradingLeg::new(TradingVenue::BinanceFutures, 100.0, 100.1, 123456);
        ctx.set_hedging_symbol("BTCUSDT");
        ctx.price_qv = QuantizedValue::from_parts(1, -2, 10005);
        ctx.amount_qv = QuantizedValue::from_parts(1, -3, 250);
        ctx.price_offset = -0.001;
        ctx.signal_ts = 999;
        ctx.exp_time = 1111;
        ctx.request_seq = 3;
        ctx.set_from_key(b"arb-fk".to_vec());

        let parsed = ArbHedgeCtx::from_bytes(ctx.to_bytes()).unwrap();
        assert_eq!(parsed.strategy_id, 11);
        assert_eq!(parsed.get_side(), Some(Side::Sell));
        assert_eq!(parsed.get_hedging_symbol(), "BTCUSDT");
        assert!((parsed.price_value() - 100.05).abs() < 1e-12);
        assert!((parsed.amount_value() - 0.25).abs() < 1e-12);
        assert_eq!(parsed.price_offset, -0.001);
        assert_eq!(parsed.signal_ts, 999);
        assert_eq!(parsed.exp_time, 1111);
        assert_eq!(parsed.request_seq, 3);
        assert!(parsed.is_maker());
        assert_eq!(parsed.from_key, b"arb-fk");
    }
}
